Feature/solve
hy-cs-team/jbtimer pull request #1
Opened 2023-11-30 00:10 UTC by cyanosj128

idle, preview, penalty, running 4단계로 나누어 작업

우선은 '초' 단위로 작업하였고, '밀리초'로 추후 작업 예정

2023-11-30 01:30 UTC, CubeDr requested changes

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +  int _elapsedPrviewTime = 0;
오타: `_elapsedPreviewTime`

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +  int _previewTime = 15;
`15` 상수화 시켜주세요

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +    final displayWidget = _recordState == RecordState.preview
`Text()`는 모든 상태 동일하게 해주시고, 기록 형식으로 바꿔주세요

https://github.com/hy-cs-team/jbtimer/blob/master/lib/extensions/format_extensions.dart 에 있는 recordFormat 사용하시면 됩니다.

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +  Timer? previewCountDownTimer;
얘는 private 안 돼야 하나요?

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +enum RecordState {
private?

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +      recordMs: _elapsedPrviewTime + _elapsedTime,
지금 초 단위이니 `* 1000`이라도 해서 넣어줍시다.

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +    _penaltyTimer?.cancel();
`_recordTimer`는 `cancel()` 안 해도 되나요?

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +    if (_recordState == RecordState.idle) {
`switch()`

2023-11-30 01:30 UTC, CubeDr commented on lib/main/record_area.dart
> +  Timer? _recordTimer;
다 `Timer`를 사용하셨는데, `Timer`는 일정 주기 별로 콜백 호출하는 애라 얘로 우리가 구현해야 하는 타이머를 만들기는 힘들어보입니다. 지금은 1초라서 콜백이 정상적으로 호출되지만 밀리초 단위로 가면 콜백이 1 밀리초마다 일어날 수는 없으니까 구현이 안됩니다. 아마 이런 이슈 때문에 1초 단위로 먼저 보내신 것 같은데, 이렇게 되면 이후에 싹 갈아엎어야 해서 지금 수정하고 가는게 좋아보입니다.

`StopWatch` 클래스가 있는데 이게 더 적합해 보입니다.
https://api.flutter.dev/flutter/dart-core/Stopwatch-class.html

2023-12-01 08:11 UTC, CubeDr requested changes

2023-12-01 08:11 UTC, CubeDr commented on lib/main/record_area.dart
> +  final Stopwatch _stopwatch = Stopwatch();
하나의 stopwatch로 가능하지 않나요?

2023-12-01 08:11 UTC, CubeDr commented on lib/main/record_area.dart
> +      dateTime: _startAt,
종료 시간을 기록하고 `_startAt`은 빼도 될 것 같습니다.

2023-12-01 08:11 UTC, CubeDr commented on lib/main/record_area.dart
> +            elapsedTime = totalDuration = 1;
`elapsedTime` 빼고는 StreamBuilder의 builder()가 호출될 때마다 새로 구하지 않아도 될 것 같습니다.
그리고 StreamBuilder를 사용하는 만큼 `snapshot`을 이용해 시간을 구하는게 좋아보입니다.

2023-12-01 08:11 UTC, CubeDr commented on lib/main/record_area.dart
> +                  Colors.transparent;
한 state에서 배경 색 애니메이션은 종목이나 사람별로 시간이 천차만별이기 때문에 큰 의미가 없고 오히려 신경을 분산시킬 것 같습니다. 빼는 것이 좋아보입니다.

2023-12-01 08:39 UTC, cyanosj128 commented on lib/main/record_area.dart
> +  final Stopwatch _stopwatch = Stopwatch();
하나로 합쳤습니다.

2023-12-01 08:39 UTC, cyanosj128 commented on lib/main/record_area.dart
> +      dateTime: _startAt,
종료 시간으로 수정하였습니다

2023-12-01 08:40 UTC, cyanosj128 commented on lib/main/record_area.dart
> +            elapsedTime = totalDuration = 1;
elapsed time을 바로 stream에게 넘겨주어 snapshot을 이용하였습니다

2023-12-01 08:40 UTC, cyanosj128 commented on lib/main/record_area.dart
> +                  Colors.transparent;
컬러 수정하였습니다

2023-12-01 08:41 UTC, CubeDr approved these changes

2023-12-01 08:56 UTC, merged